### ISSUE TITLE
Error when reloading a trained model for wavenet

### ISSUE THREAD

**Issue by zhang-jian** [bfs18/nsynth_wavenet#3]
Got errors when running eval_wavenet.py using the latest code:
<pre>
Traceback (most recent call last):
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/system/usr/tools/anaconda3/lib/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1024] rhs shape= [512]
	 [[Node: save/Assign_45 = Assign[T=DT_FLOAT, _class=["loc:@dilated_conv_3/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](dilated_conv_3/biases, save/RestoreV2_45/_457)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval_wavenet.py", line 96, in <module>
    generate(args)
  File "eval_wavenet.py", line 69, in generate
    fastgen.synthesis(hparams, encoding, save_names, checkpoint_path)
  File "/system/usr/works/tensorflow_wavenet/nsynth_wavenet-master/wavenet/fastgen.py", line 120, in synthesis
    saver.restore(sess, checkpoint_path)
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1024] rhs shape= [512]
	 [[Node: save/Assign_45 = Assign[T=DT_FLOAT, _class=["loc:@dilated_conv_3/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](dilated_conv_3/biases, save/RestoreV2_45/_457)]]

Caused by op 'save/Assign_45', defined at:
  File "eval_wavenet.py", line 96, in <module>
    generate(args)
  File "eval_wavenet.py", line 69, in generate
    fastgen.synthesis(hparams, encoding, save_names, checkpoint_path)
  File "/system/usr/works/tensorflow_wavenet/nsynth_wavenet-master/wavenet/fastgen.py", line 119, in synthesis
    saver = tf.train.Saver(shadow_var_dict)
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/ops/state_ops.py", line 271, in assign
    validate_shape=validate_shape)
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/ops/gen_state_ops.py", line 45, in assign
    use_locking=use_locking, name=name)
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/system/usr/tools/anaconda3/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1024] rhs shape= [512]
	 [[Node: save/Assign_45 = Assign[T=DT_FLOAT, _class=["loc:@dilated_conv_3/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](dilated_conv_3/biases, save/RestoreV2_45/_457)]]
</pre>

Thanks

**Comment by bfs18** [comment]
I modified gate width according to the parallel wavenet paper.
If you want to use old models, you can uncomment this L135 in wavenet/wavenet.py , and comment L135.
You can check the comments.
https://github.com/bfs18/nsynth_wavenet/blob/b599ecbaed7a21895329954a84052d876c60a650/wavenet/wavenet.py#L133

**Comment by bfs18** [comment]
close
