### ISSUE TITLE
SyntaxError: invalid syntax while running eval

### ISSUE THREAD

**Issue by ishandutta2007** [bfs18/nsynth_wavenet#30]
I downloaded pretrained model :  https://drive.google.com/file/d/17bt6laBcTcjZCsLUzdTjtaH2hQQyki8E/view
created a directory `PWN_LOGDIR` and then executed
 `python3 eval_parallel_wavenet.py --ckpt_dir PWN_LOGDIR --source_path tests/test_data
`
> Traceback (most recent call last):
>   File "eval_parallel_wavenet.py", line 7, in <module>
>     from wavenet import fastgen, parallelgen
>   File "/Users/ishandutta2007/Documents/Projects/nsynth_wavenet/wavenet/fastgen.py", line 8, in <module>
>     from wavenet import wavenet
>   File "/Users/ishandutta2007/Documents/Projects/nsynth_wavenet/wavenet/wavenet.py", line 39
>     **conv_args, name=name_patt.format("resize_conv"))
>                ^
> SyntaxError: invalid syntax
> 

My python version is 3.4.2

`pyenv version`
> 3.4.2 (set by /Users/ishandutta2007/.pyenv/version)

**Comment by ishandutta2007** [comment]
I had python 3.4.2, You need python 3.5+ for double asterics unpacking to be recognised.
